INSERT INTO product (id, name, description, price, brand, category, image_url) VALUES
(RANDOM_UUID(), 'iPhone 14', 'Latest Apple smartphone with advanced camera.', 999.99, 'Apple', 'ELECTRONICS', 'https://images.pexels.com/photos/16005007/pexels-photo-16005007/free-photo-of-apple-iphone-14-pro-max-mobile-phone.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),
(RANDOM_UUID(), 'Galaxy S22', 'Samsung flagship Android phone.', 899.99, 'Samsung', 'ELECTRONICS', 'https://images.pexels.com/photos/13780425/pexels-photo-13780425.jpeg?auto=compress&cs=tinysrgb&w=600'),
(RANDOM_UUID(), 'Pixel 6', 'Google Pixel with Android 12.', 799.99, 'Google', 'ELECTRONICS', 'https://a.media-amazon.com/images/I/41pOyYd1OsL._SX300_SY300_QL70_FMwebp_.jpg'),
(RANDOM_UUID(), 'OnePlus 9', 'Fast and smooth OnePlus smartphone.', 699.99, 'OnePlus', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBf-gkra6BXea-w7c4tSYbJLDNCfwx12TQ9w&s'),
(RANDOM_UUID(), 'MacBook Pro', 'Apple laptop with M1 chip.', 1299.99, 'Apple', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkberjqtYBogkjt8TE93Yjr-SMX92dOMGOTA&s'),
(RANDOM_UUID(), 'Dell XPS 13', 'Powerful ultrabook laptop.', 1199.99, 'Dell', 'ELECTRONICS', 'https://pctech.co.in/image/cache/catalog/Laptops/DELL/dell-xps-15-9530-laptop-01-800x800w.jpg'),
(RANDOM_UUID(), 'HP Pavilion', 'Affordable HP laptop.', 649.99, 'HP', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSb4gnDPuJzLhLmm3rZzBw5udo7n8Vaa1G2lg&s'),
(RANDOM_UUID(), 'Sony WH-1000XM5', 'Noise-cancelling headphones.', 349.99, 'Sony', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRNtvab3ayuNpyai0mVPIVTEGbRKsq5IU8tw&s'),
(RANDOM_UUID(), 'Bose QuietComfort 45', 'Premium noise-cancelling headphones.', 329.99, 'Bose', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMh0aQAVmMKNmycw5UpUwHUbVz7iFdVgVC4A&s'),
(RANDOM_UUID(), 'Canon EOS R5', 'Professional mirrorless camera.', 3899.99, 'Canon', 'ELECTRONICS', 'https://example.com/canonr5.jpg'),
(RANDOM_UUID(), 'Nike Air Max', 'Trendy Nike running shoes.', 129.99, 'Nike', 'FASHION', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQjmMZbJXcQ3nXPMyMUT1BteaGCyhLmzHm2Q&s'),
(RANDOM_UUID(), 'Adidas Ultraboost', 'Comfortable running sneakers.', 139.99, 'Adidas', 'FASHION', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-dZL5qjUXISq4V72TT_nWH0NnujGE2lRA5g&s'),
(RANDOM_UUID(), 'Puma Tracksuit', 'Stylish and sporty.', 89.99, 'Puma', 'FASHION', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRaJ6YYWfbMRS9ZStWTcXQeOnubCM7keFvHw&s'),
(RANDOM_UUID(), 'Zara Denim Jacket', 'Trendy men’s denim jacket.', 59.99, 'Zara', 'FASHION', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8JivnIn3C2IgJR6NQAT3tuQjnCwBI7k3p1g&s'),
(RANDOM_UUID(), 'H&M Hoodie', 'Casual wear hoodie.', 39.99, 'H&M', 'FASHION', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY6-5l0obTRbOIjtnZa3_lJyGuG7H76rW1NA&s'),
(RANDOM_UUID(), 'Uniqlo T-Shirt', 'Premium cotton t-shirt.', 19.99, 'Uniqlo', 'FASHION', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2_PXdsu-KW049jEIpzr3P2r8Bs6sHsn-rRw&s'),
(RANDOM_UUID(), 'Levi’s Jeans', 'Classic fit denim jeans.', 69.99, 'Levis', 'FASHION', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaPUwFkmiosbgZn7CQNEDGeb5g2rW6z918GA&s'),
(RANDOM_UUID(), 'Under Armour Shorts', 'Athletic performance shorts.', 29.99, 'Under Armour', 'FASHION', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7R9mRdW7jiNeXhGz_TjPvre_zC55JCue_mg&s'),
(RANDOM_UUID(), 'The Great Gatsby', 'Classic novel by F. Scott Fitzgerald.', 9.99, 'Scribner', 'BOOKS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKi5lknrw7SIwZ01RQRqyvtXz2bFxrUsGVpA&s'),
(RANDOM_UUID(), 'To Kill a Mockingbird', 'Pulitzer Prize-winning novel.', 12.99, 'Harper Lee', 'BOOKS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVffgmWG5N3zERvr5TEnTAsXLPwyXq_AQHNQ&s'),
(RANDOM_UUID(), '1984', 'Dystopian novel by George Orwell.', 10.99, 'George Orwell', 'BOOKS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpgonH82eJD0fDNyw-xLIu9EK-NQVg3pFxIA&s'),
(RANDOM_UUID(), 'Atomic Habits', 'Self-help bestseller.', 16.99, 'James Clear', 'BOOKS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQBoTKBmo1tiL9U5vaACz7j4lWFbcr62Sm4g&s'),
(RANDOM_UUID(), 'The Alchemist', 'Inspiring story by Paulo Coelho.', 11.99, 'HarperOne', 'BOOKS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbaD17umC0n2pRjZtvFO3cprbqfPVvRUjTOg&s'),
(RANDOM_UUID(), 'Clean Code', 'Guide to writing better code.', 34.99, 'Robert C. Martin', 'BOOKS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwkWKXgzjLGiN40SYLFTxHYeRwPv1G29niow&s'),
(RANDOM_UUID(), 'Harry Potter 1', 'Fantasy novel for children.', 14.99, 'J.K. Rowling', 'BOOKS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIHCBa_nEken_4j87lIQlHibKGLga7WeqUvQ&s'),
(RANDOM_UUID(), 'Harry Potter 2', 'Sequel to Harry Potter.', 15.99, 'J.K. Rowling', 'BOOKS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVZfAfJ_pVz2e1oUPQqLdnwbeOQeGYHtXVsQ&s'),
(RANDOM_UUID(), 'Logitech MX Master 3', 'High-performance wireless mouse.', 99.99, 'Logitech', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuBrLrEBmCMT-g4Z5T-760ybhXQWgQ2MgVzA&s'),
(RANDOM_UUID(), 'Kindle Paperwhite', 'E-reader with front light.', 129.99, 'Amazon', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAiMk5WKQPdxReLnmqVkOXXKvWd35BkjjYVg&s'),
(RANDOM_UUID(), 'Samsung Galaxy Watch', 'Smartwatch with fitness tracking.', 229.99, 'Samsung', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9AbRt0-WH8LSQpRJDOHDEiWOcEZZUTBIN0Q&s'),
(RANDOM_UUID(), 'Apple Watch SE', 'Smartwatch with fitness and health features.', 249.99, 'Apple', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEjl8jrX4KmvVT6DA039_az5PWnwupSUcf5w&s'),
(RANDOM_UUID(), 'Asus ROG Phone', 'Gaming smartphone.', 899.99, 'Asus', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo3NNhCVhlVbrqrtRlgMXGI85jOZNGbvMp2w&s'),
(RANDOM_UUID(), 'MSI Gaming Laptop', 'High-performance laptop.', 1399.99, 'MSI', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO_dTjr8RQsAOwO-9FDEpT8J-kk3iothIlGg&s'),
(RANDOM_UUID(), 'Reebok Classic', 'Old-school sneakers.', 69.99, 'Reebok', 'FASHION', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHkqLHW-3rmppxcoWFV0g5UhgJ2o-za0nZ2A&s'),
(RANDOM_UUID(), 'Tata Story', 'Inspiring biography of Tata Group.', 13.99, 'Penguin', 'BOOKS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5zASwvgNiZjmV-jA_lXAuNrlRHvEI1xjr6A&s'),
(RANDOM_UUID(), 'Think and Grow Rich', 'Classic self-help book.', 8.99, 'Napoleon Hill', 'BOOKS', 'https://d1fa9n6k2ql7on.cloudfront.net/tgr-think-and-grow-rich-by-napoleon-hill-header.jpg'),
(RANDOM_UUID(), 'Sony PS5', 'Next-gen gaming console.', 499.99, 'Sony', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgg56yfmOe9ZY6nA3nS87C9u2aEEALM5O8dQ&s'),
(RANDOM_UUID(), 'Xbox Series X', 'Microsoft gaming console.', 499.99, 'Microsoft', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoJKNsRj2CKeZaDXVvn25hNFjIo9esH_jVHw&s'),
(RANDOM_UUID(), 'Samsung TV 55"', 'Smart UHD television.', 599.99, 'Samsung', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRd0rKoVwBcfkTEpPnCqCqt0G7WJ7e89fNqIg&s'),
(RANDOM_UUID(), 'LG Refrigerator', 'Smart double-door fridge.', 899.99, 'LG', 'ELECTRONICS', 'https://www.lg.com/content/dam/channel/wcms/sa_en/images/refrigerators/ls25cbbsiv/L01.jpg/_jcr_content/renditions/thum-1600x1062.jpeg'),
(RANDOM_UUID(), 'Fitbit Charge 5', 'Fitness tracker band.', 149.99, 'Fitbit', 'ELECTRONICS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiegBKV02H2EpUJ3AUzaclwaWiMLC8HZNzpg&s');
